# Generated by Django 5.0.3 on 2024-03-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='cv',
            field=models.FileField(null=True, upload_to='cv/'),
        ),
    ]
