# Generated by Django 5.0.3 on 2024-04-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_alter_colab_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='linkedin',
            field=models.CharField(max_length=512),
        ),
    ]
