# Generated by Django 5.0.3 on 2024-04-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plans_image_limit_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
