# Generated by Django 5.0.3 on 2024-04-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plans_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribes',
            name='remain_images',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
